database:
  path: "/home/courses/.local/share/gourmand/recipes.db"

mbox:
  SRC: "ia_raw.mbox"
  path: "/home/michel/Mail"
  
server:
  protocolVersion: "2024-11-05"
  name: "perso"
  version: "1.0.2"
